spring:
  datasource:
    url: jdbc:mysql://localhost:${DB_PORT}/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
#    show-sql: false
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true

# bind and display error message
server:
  error:
    include-message: "always"
    include-binding-errors: "always"